import defaultMdxComponents from "fumadocs-ui/mdx";
import { ComponentPreview } from "@/components/docs/component-preview";
import { PropsTable } from "@/components/docs/props-table";
import { CodeBlock } from "@/components/docs/code-block";
import { ComponentsTable } from "@/components/docs/components-table";
import { DialogDefaultDemo, DialogHideControlsDemo } from "@/components/demos/dialog-demo";
import {
  ScrollArea,
  ScrollAreaViewport,
  Scrollbar,
  ScrollThumb,
  ScrollCorner,
} from "@/components/ui/scroll-area";
import {
  CardDefaultDemo,
  BadgeColorsDemo,
  TooltipDemo,
  SwitchDemo,
  TabsDemo,
  InputBasicDemo,
  InputIconsDemo,
  InputPrefixSuffixDemo,
  ButtonBasicDemo,
  ButtonIconsDemo,
  ButtonLoaderDemo,
  AlertDemo,
  CheckboxDemo,
  AvatarDemo,
  AvatarGroupDemo,
  ProgressDemo,
  SelectDemo,
  AccordionDemo,
  PopoverDemo,
  RadioGroupDemo,
  SliderDemo,
  SliderWithLabelDemo,
  TextareaDemo,
  SeparatorDemo,
  AccordionPastelDemo,
  RadioGroupColorsDemo,
  SliderPinkDemo,
  SliderRangeDemo,
  TextareaPastelDemo,
  TextareaDisabledDemo,
  SeparatorVerticalDemo,
  SeparatorColorsDemo,
  BarChartDemo,
  LineChartDemo,
  DonutChartDemo,
  SkeletonDemo,
  TableDemo,
  BreadcrumbDemo,
  ToggleDemo,
  DropdownMenuDemo,
  HoverCardDemo,
  ScrollAreaDemo,
  PaginationDemo,
  PaginationEllipsisDemo,
  SonnerDemo,
  SheetDemo,
  MenubarDemo,
  ContextMenuDemo,
  ToggleGroupDemo,
  CollapsibleDemo,
} from "@/components/demos/all-demos";
import type { MDXComponents } from "mdx/types";

export function getMDXComponents(components?: MDXComponents): MDXComponents {
  return {
    ...defaultMdxComponents,
    ComponentPreview,
    PropsTable,
    CodeBlock,
    ComponentsTable,
    DialogDefaultDemo,
    DialogHideControlsDemo,
    CardDefaultDemo,
    BadgeColorsDemo,
    TooltipDemo,
    SwitchDemo,
    TabsDemo,
    InputBasicDemo,
    InputIconsDemo,
    InputPrefixSuffixDemo,
    ButtonBasicDemo,
    ButtonIconsDemo,
    ButtonLoaderDemo,
    AlertDemo,
    CheckboxDemo,
    AvatarDemo,
    AvatarGroupDemo,
    ProgressDemo,
    SelectDemo,
    AccordionDemo,
    PopoverDemo,
    RadioGroupDemo,
    SliderDemo,
    SliderWithLabelDemo,
    TextareaDemo,
    SeparatorDemo,
    AccordionPastelDemo,
    RadioGroupColorsDemo,
    SliderPinkDemo,
    SliderRangeDemo,
    TextareaPastelDemo,
    TextareaDisabledDemo,
    SeparatorVerticalDemo,
    SeparatorColorsDemo,
    BarChartDemo,
    LineChartDemo,
    DonutChartDemo,
    SkeletonDemo,
    TableDemo,
    BreadcrumbDemo,
    ToggleDemo,
    DropdownMenuDemo,
    HoverCardDemo,
    ScrollAreaDemo,
    PaginationDemo,
    PaginationEllipsisDemo,
    SonnerDemo,
    SheetDemo,
    MenubarDemo,
    ContextMenuDemo,
    ToggleGroupDemo,
    CollapsibleDemo,
    ScrollArea,
    ScrollAreaViewport,
    Scrollbar,
    ScrollThumb,
    ScrollCorner,
    ...components,
  };
}